### ISSUE TITLE
Godot 4-compatible version?

### ISSUE THREAD

**Issue by Rubrickus** [don-tnowe/godot-dictionary-inspector#1]
I'm dying to try this out, but I'm working in Godot 4. I took a stab at doing the conversion myself, but while some of the changes are trivial (e.g. tool -> @tool), I quickly got out of my depth with some of the more significant differences (new types, new semantics for export, etc.). I'm pretty new at Godot, and haven't built any editor plugins myself, so I was a little uneasy hacking away at it.

Any chance you'll make a Godot 4 version yourself? FWIW, I think that would increase the chances of getting this (or something similar) accepted into the Godot 4 engine eventually (which I very much hope for!).

**Comment by don-tnowe** [comment]
Hello!

Yep, it is planned. I intend to start converting all of my plugins (*and updating the one with the 4.0 version falling behind*) when Godot 4.0 enters Release Candidate state. 

It looks like the betas now support GLES 3 properly, so I might port some earlier because my work (*and currently only*) computer can now run it!

**Comment by don-tnowe** [comment]
Fixed by commit 80b99e111b3decfa75f2c42ac06e79f8602cea7e. Feel free to report issues, and enjoy!
