### ISSUE TITLE
Removing this add on will cause editor errors when creating new nodes

### ISSUE THREAD

**Issue by cf-richard** [don-tnowe/godot-dictionary-inspector#13]
Import this add on
Remove it via deleting the associated folder
Create a node

Will get the error

Cannot open file 'res://DictionaryInspector/addons/TypedDictionary/TypedDictionaryArrayButtonMover.cs'.
  Failed to read file: 'res://DictionaryInspector/addons/TypedDictionary/TypedDictionaryArrayButtonMover.cs'.
  Cannot load C# script file 'res://DictionaryInspector/addons/TypedDictionary/TypedDictionaryArrayButtonMover.cs'.
  Failed loading resource: res://DictionaryInspector/addons/TypedDictionary/TypedDictionaryArrayButtonMover.cs. Make sure resources have been imported by opening the project in the editor at least once.
  editor/create_dialog.cpp:246 - Condition "scr.is_null()" is true.

**Comment by don-tnowe** [comment]
I'm confused as to why:

- Files you are referring to have the C# extension, since the addon is entirely in GDScript
- Files you are referring to being in `res://DictionaryInspector/addons/` but still causing errors when removing the "associated" folder, since the addon is supposed to be in `res://addons/dictionary_inspector/`

Most addons with a plugin are likely to create errors when deleted - make sure you disable the plugin in Project Settings before that.
