### ISSUE TITLE
[REQUEST] Add a delete button

### ISSUE THREAD

**Issue by leonardoraele** [don-tnowe/godot-dictionary-inspector#15]
It's very counter-intuitive that the delete button is inside the dropdown to change the value type, (it took me about 5 minutes to find it) it would be better if each dictionary entry had its own delete button.

**Comment by don-tnowe** [comment]
Duplicate: #11

It's actually done in the same way the unmodified inspector has it for both collection types. I originally kept it that way since extra buttons add extra clutter and adding an extra step to deletion makes unintentional deletion more difficult.

Admittedly, for dictionaries it's now too hidden.

**Comment by don-tnowe** [comment]
Currently, this looks like this. Type switcher moved to match default inspector editor, and deletion buttons visible when editing an entry. Kept them under edit mode for some safety, since undo/redo currently isn't supported.

![gif2](https://github.com/don-tnowe/godot-dictionary-inspector/assets/67479453/82633116-a2dc-437a-8ef1-078cab218e01)

**Comment by leonardoraele** [comment]
I think the way it is in the gif is a big improvement. I agree about hiding the delete button in the edit mode to prevent accidental deletion.
