### ISSUE TITLE
Typed Object arrays are not editable, new custom Resources cannot be created from Resource Picker

### ISSUE THREAD

**Issue by WerDei** [don-tnowe/godot-dictionary-inspector#16]
Versions tested: 4.2 and 4.3-beta3

How it looks without the plugin:
![image](https://github.com/user-attachments/assets/5e2768a0-8d58-418f-ab02-ecc10b02c05b)

And with:
![image](https://github.com/user-attachments/assets/11890b8b-f84f-4631-96da-0dd64a8a92bd)

This error is thrown in the console:
```
Cannot get class 'CustomResource'.
Cannot get class 'CustomResource'.
```

Also, this addon seemingly doesen't like custom resources in general, since it's impossible to pick them in the type picker (true for both Array and Dictionary).

**Comment by don-tnowe** [comment]
More details:

- Resources do open correctly, showing all properties (*including Script and Resource Name*), as seen in the screenshot attached to the issue.
- Creating a new Resource through the popup menu does only work for non-custom resources, and I can reproduce this.
- Adding resources in generic arrays is possible (*custom resources are only through drag-and-drop*), but not to typed arrays: the picker's Resource is changed, but upon re-opening the editor it gets removed from the array. This happens to any resource type if array is typed.
    - Error appears when adding to ANY array type: `editor/editor_resource_picker.cpp:458 - Condition "inheritors_array.is_empty()" is true.`, so it is likely not the cause of removal in typed arrays.
    - Typed array don't work at all. Editing any of the items saves as the type's default value.
    
I guess [another type of top-level arrays](https://github.com/don-tnowe/godot-dictionary-inspector/commit/8c9086caaa7486f2ed3fef731c33d857073cbcf0) should go away.

**Comment by don-tnowe** [comment]
Since I later found this to not work with typed arrays, I will remove typed array support for the time being - better to have dictionaries inside be edited without the plugin UI, rather than not at all.

Pulled this to [Godot-4 branch](https://github.com/don-tnowe/godot-dictionary-inspector/tree/godot-4).

Regarding Resource Picker, the `ClassDB` class seems to not store data of custom classes in the editor context. I'm sure this used to work in early Godot 4, but to fix this I would need to create an engine PR.

**Comment by don-tnowe** [comment]
I split the issue into #17, #18, since this highlights two improper behaviours that should be discussed separately.
